"""empty message

Revision ID: 6b530fe14b7a
Revises: d952e3332d45
Create Date: 2022-04-15 20:54:46.873227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b530fe14b7a'
down_revision = 'd952e3332d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Todo', sa.Column('completed', sa.Boolean(), nullable=True))
    op.drop_column('Todo', 'task_done')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Todo', sa.Column('task_done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Todo', 'completed')
    # ### end Alembic commands ###
