"""empty message

Revision ID: be012d5699d0
Revises: 
Create Date: 2022-04-07 13:38:02.506879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be012d5699d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Column('todo_name', sa.String(), autoincrement=False, nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Todo', sa.Column('todo_name', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Todo', 'todo')
    # ### end Alembic commands ###
